export const flagsData: { [key: string]: string } ={
    "Moldova": "https://flagcdn.com/md.svg",
    "United States": "https://flagcdn.com/us.svg",
    "Mayotte": "https://flagcdn.com/yt.svg",
    "Nauru": "https://flagcdn.com/nr.svg",
    "Mozambique": "https://flagcdn.com/mz.svg",
    "Brazil": "https://flagcdn.com/br.svg",
    "Cape Verde": "https://flagcdn.com/cv.svg",
    "Equatorial Guinea": "https://flagcdn.com/gq.svg",
    "Albania": "https://flagcdn.com/al.svg",
    "United States Virgin Islands": "https://flagcdn.com/vi.svg",
    "Niue": "https://flagcdn.com/nu.svg",
    "Palau": "https://flagcdn.com/pw.svg",
    "Nigeria": "https://flagcdn.com/ng.svg",
    "British Virgin Islands": "https://flagcdn.com/vg.svg",
    "Gambia": "https://flagcdn.com/gm.svg",
    "Somalia": "https://flagcdn.com/so.svg",
    "Yemen": "https://flagcdn.com/ye.svg",
    "Malaysia": "https://flagcdn.com/my.svg",
    "Dominica": "https://flagcdn.com/dm.svg",
    "United Kingdom": "https://flagcdn.com/gb.svg",
    "Madagascar": "https://flagcdn.com/mg.svg",
    "Western Sahara": "https://flagcdn.com/eh.svg",
    "Cyprus": "https://flagcdn.com/cy.svg",
    "Antigua and Barbuda": "https://flagcdn.com/ag.svg",
    "Ireland": "https://flagcdn.com/ie.svg",
    "Paraguay": "https://flagcdn.com/py.svg",
    "Sri Lanka": "https://flagcdn.com/lk.svg",
    "South Africa": "https://flagcdn.com/za.svg",
    "Kuwait": "https://flagcdn.com/kw.svg",
    "Algeria": "https://flagcdn.com/dz.svg",
    "Croatia": "https://flagcdn.com/hr.svg",
    "Martinique": "https://flagcdn.com/mq.svg",
    "Sierra Leone": "https://flagcdn.com/sl.svg",
    "Northern Mariana Islands": "https://flagcdn.com/mp.svg",
    "Rwanda": "https://flagcdn.com/rw.svg",
    "Syria": "https://flagcdn.com/sy.svg",
    "Saint Vincent and the Grenadines": "https://flagcdn.com/vc.svg",
    "Kosovo": "https://flagcdn.com/xk.svg",
    "Saint Lucia": "https://flagcdn.com/lc.svg",
    "Honduras": "https://flagcdn.com/hn.svg",
    "Jordan": "https://flagcdn.com/jo.svg",
    "Tuvalu": "https://flagcdn.com/tv.svg",
    "Nepal": "https://flagcdn.com/np.svg",
    "Liberia": "https://flagcdn.com/lr.svg",
    "Heard Island and McDonald Islands": "https://flagcdn.com/hm.svg",
    "Austria": "https://flagcdn.com/at.svg",
    "Guernsey": "https://flagcdn.com/gg.svg",
    "Central African Republic": "https://flagcdn.com/cf.svg",
    "Mauritania": "https://flagcdn.com/mr.svg",
    "Djibouti": "https://flagcdn.com/dj.svg",
    "Fiji": "https://flagcdn.com/fj.svg",
    "Norway": "https://flagcdn.com/no.svg",
    "Latvia": "https://flagcdn.com/lv.svg",
    "Falkland Islands": "https://flagcdn.com/fk.svg",
    "Kazakhstan": "https://flagcdn.com/kz.svg",
    "Åland Islands": "https://flagcdn.com/ax.svg",
    "Turkmenistan": "https://flagcdn.com/tm.svg",
    "Cocos (Keeling) Islands": "https://flagcdn.com/cc.svg",
    "Bulgaria": "https://flagcdn.com/bg.svg",
    "Tokelau": "https://flagcdn.com/tk.svg",
    "New Caledonia": "https://flagcdn.com/nc.svg",
    "Barbados": "https://flagcdn.com/bb.svg",
    "São Tomé and Príncipe": "https://flagcdn.com/st.svg",
    "Antarctica": "https://flagcdn.com/aq.svg",
    "Brunei": "https://flagcdn.com/bn.svg",
    "Bhutan": "https://flagcdn.com/bt.svg",
    "Cameroon": "https://flagcdn.com/cm.svg",
    "Argentina": "https://flagcdn.com/ar.svg",
    "Azerbaijan": "https://flagcdn.com/az.svg",
    "Mexico": "https://flagcdn.com/mx.svg",
    "Morocco": "https://flagcdn.com/ma.svg",
    "Guatemala": "https://flagcdn.com/gt.svg",
    "Kenya": "https://flagcdn.com/ke.svg",
    "Malta": "https://flagcdn.com/mt.svg",
    "Czechia": "https://flagcdn.com/cz.svg",
    "Gibraltar": "https://flagcdn.com/gi.svg",
    "Aruba": "https://flagcdn.com/aw.svg",
    "Saint Barthélemy": "https://flagcdn.com/bl.svg",
    "Monaco": "https://flagcdn.com/mc.svg",
    "United Arab Emirates": "https://flagcdn.com/ae.svg",
    "South Sudan": "https://flagcdn.com/ss.svg",
    "Puerto Rico": "https://flagcdn.com/pr.svg",
    "El Salvador": "https://flagcdn.com/sv.svg",
    "France": "https://flagcdn.com/fr.svg",
    "Niger": "https://flagcdn.com/ne.svg",
    "Ivory Coast": "https://flagcdn.com/ci.svg",
    "South Georgia": "https://flagcdn.com/gs.svg",
    "Botswana": "https://flagcdn.com/bw.svg",
    "British Indian Ocean Territory": "https://flagcdn.com/io.svg",
    "Uzbekistan": "https://flagcdn.com/uz.svg",
    "Tunisia": "https://flagcdn.com/tn.svg",
    "Hong Kong": "https://flagcdn.com/hk.svg",
    "North Macedonia": "https://flagcdn.com/mk.svg",
    "Suriname": "https://flagcdn.com/sr.svg",
    "Belgium": "https://flagcdn.com/be.svg",
    "American Samoa": "https://flagcdn.com/as.svg",
    "Solomon Islands": "https://flagcdn.com/sb.svg",
    "Ukraine": "https://flagcdn.com/ua.svg",
    "Finland": "https://flagcdn.com/fi.svg",
    "Burkina Faso": "https://flagcdn.com/bf.svg",
    "Bosnia and Herzegovina": "https://flagcdn.com/ba.svg",
    "Iran": "https://flagcdn.com/ir.svg",
    "Cuba": "https://flagcdn.com/cu.svg",
    "Eritrea": "https://flagcdn.com/er.svg",
    "Slovakia": "https://flagcdn.com/sk.svg",
    "Lithuania": "https://flagcdn.com/lt.svg",
    "Saint Martin": "https://flagcdn.com/mf.svg",
    "Pitcairn Islands": "https://flagcdn.com/pn.svg",
    "Guinea-Bissau": "https://flagcdn.com/gw.svg",
    "Montserrat": "https://flagcdn.com/ms.svg",
    "Turkey": "https://flagcdn.com/tr.svg",
    "Philippines": "https://flagcdn.com/ph.svg",
    "Vanuatu": "https://flagcdn.com/vu.svg",
    "Bolivia": "https://flagcdn.com/bo.svg",
    "Saint Kitts and Nevis": "https://flagcdn.com/kn.svg",
    "Romania": "https://flagcdn.com/ro.svg",
    "Cambodia": "https://flagcdn.com/kh.svg",
    "Zimbabwe": "https://flagcdn.com/zw.svg",
    "Jersey": "https://flagcdn.com/je.svg",
    "Kyrgyzstan": "https://flagcdn.com/kg.svg",
    "Caribbean Netherlands": "https://flagcdn.com/bq.svg",
    "Guyana": "https://flagcdn.com/gy.svg",
    "United States Minor Outlying Islands": "https://flagcdn.com/um.svg",
    "Armenia": "https://flagcdn.com/am.svg",
    "Lebanon": "https://flagcdn.com/lb.svg",
    "Montenegro": "https://flagcdn.com/me.svg",
    "Greenland": "https://flagcdn.com/gl.svg",
    "Papua New Guinea": "https://flagcdn.com/pg.svg",
    "Zambia": "https://flagcdn.com/zm.svg",
    "Trinidad and Tobago": "https://flagcdn.com/tt.svg",
    "French Southern and Antarctic Lands": "https://flagcdn.com/tf.svg",
    "Peru": "https://flagcdn.com/pe.svg",
    "Sweden": "https://flagcdn.com/se.svg",
    "Sudan": "https://flagcdn.com/sd.svg",
    "Saint Pierre and Miquelon": "https://flagcdn.com/pm.svg",
    "Oman": "https://flagcdn.com/om.svg",
    "India": "https://flagcdn.com/in.svg",
    "Taiwan": "https://flagcdn.com/tw.svg",
    "Mongolia": "https://flagcdn.com/mn.svg",
    "Senegal": "https://flagcdn.com/sn.svg",
    "Tanzania": "https://flagcdn.com/tz.svg",
    "Canada": "https://flagcdn.com/ca.svg",
    "Costa Rica": "https://flagcdn.com/cr.svg",
    "China": "https://flagcdn.com/cn.svg",
    "Colombia": "https://flagcdn.com/co.svg",
    "Myanmar": "https://flagcdn.com/mm.svg",
    "Russia": "https://flagcdn.com/ru.svg",
    "North Korea": "https://flagcdn.com/kp.svg",
    "Cayman Islands": "https://flagcdn.com/ky.svg",
    "Bouvet Island": "https://flagcdn.com/bv.svg",
    "Belarus": "https://flagcdn.com/by.svg",
    "Portugal": "https://flagcdn.com/pt.svg",
    "Eswatini": "https://flagcdn.com/sz.svg",
    "Poland": "https://flagcdn.com/pl.svg",
    "Switzerland": "https://flagcdn.com/ch.svg",
    "Republic of the Congo": "https://flagcdn.com/cg.svg",
    "Venezuela": "https://flagcdn.com/ve.svg",
    "Panama": "https://flagcdn.com/pa.svg",
    "Netherlands": "https://flagcdn.com/nl.svg",
    "Samoa": "https://flagcdn.com/ws.svg",
    "Denmark": "https://flagcdn.com/dk.svg",
    "Luxembourg": "https://flagcdn.com/lu.svg",
    "Faroe Islands": "https://flagcdn.com/fo.svg",
    "Slovenia": "https://flagcdn.com/si.svg",
    "Togo": "https://flagcdn.com/tg.svg",
    "Thailand": "https://flagcdn.com/th.svg",
    "Wallis and Futuna": "https://flagcdn.com/wf.svg",
    "Bahamas": "https://flagcdn.com/bs.svg",
    "Tonga": "https://flagcdn.com/to.svg",
    "Greece": "https://flagcdn.com/gr.svg",
    "San Marino": "https://flagcdn.com/sm.svg",
    "Réunion": "https://flagcdn.com/re.svg",
    "Vatican City": "https://flagcdn.com/va.svg",
    "Burundi": "https://flagcdn.com/bi.svg",
    "Bahrain": "https://flagcdn.com/bh.svg",
    "Marshall Islands": "https://flagcdn.com/mh.svg",
    "Turks and Caicos Islands": "https://flagcdn.com/tc.svg",
    "Isle of Man": "https://flagcdn.com/im.svg",
    "Haiti": "https://flagcdn.com/ht.svg",
    "Afghanistan": "https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_the_Taliban.svg",
    "Israel": "https://flagcdn.com/il.svg",
    "Libya": "https://flagcdn.com/ly.svg",
    "Uruguay": "https://flagcdn.com/uy.svg",
    "Norfolk Island": "https://flagcdn.com/nf.svg",
    "Nicaragua": "https://flagcdn.com/ni.svg",
    "Cook Islands": "https://flagcdn.com/ck.svg",
    "Laos": "https://flagcdn.com/la.svg",
    "Christmas Island": "https://flagcdn.com/cx.svg",
    "Saint Helena, Ascension and Tristan da Cunha": "https://flagcdn.com/sh.svg",
    "Anguilla": "https://flagcdn.com/ai.svg",
    "Micronesia": "https://flagcdn.com/fm.svg",
    "Germany": "https://flagcdn.com/de.svg",
    "Guam": "https://flagcdn.com/gu.svg",
    "Kiribati": "https://flagcdn.com/ki.svg",
    "Sint Maarten": "https://flagcdn.com/sx.svg",
    "Spain": "https://flagcdn.com/es.svg",
    "Jamaica": "https://flagcdn.com/jm.svg",
    "Palestine": "https://flagcdn.com/ps.svg",
    "French Guiana": "https://flagcdn.com/gf.svg",
    "Andorra": "https://flagcdn.com/ad.svg",
    "Chile": "https://flagcdn.com/cl.svg",
    "Lesotho": "https://flagcdn.com/ls.svg",
    "Australia": "https://flagcdn.com/au.svg",
    "Grenada": "https://flagcdn.com/gd.svg",
    "Ghana": "https://flagcdn.com/gh.svg",
    "Seychelles": "https://flagcdn.com/sc.svg",
    "Angola": "https://flagcdn.com/ao.svg",
    "Bermuda": "https://flagcdn.com/bm.svg",
    "Pakistan": "https://flagcdn.com/pk.svg",
    "Mali": "https://flagcdn.com/ml.svg",
    "Saudi Arabia": "https://flagcdn.com/sa.svg",
    "Curaçao": "https://flagcdn.com/cw.svg",
    "South Korea": "https://flagcdn.com/kr.svg",
    "Ethiopia": "https://flagcdn.com/et.svg",
    "Guadeloupe": "https://flagcdn.com/gp.svg",
    "Bangladesh": "https://flagcdn.com/bd.svg",
    "New Zealand": "https://flagcdn.com/nz.svg",
    "Comoros": "https://flagcdn.com/km.svg",
    "Belize": "https://flagcdn.com/bz.svg",
    "Uganda": "https://flagcdn.com/ug.svg",
    "Singapore": "https://flagcdn.com/sg.svg",
    "Liechtenstein": "https://flagcdn.com/li.svg",
    "Hungary": "https://flagcdn.com/hu.svg",
    "Iceland": "https://flagcdn.com/is.svg",
    "Tajikistan": "https://flagcdn.com/tj.svg",
    "Namibia": "https://flagcdn.com/na.svg",
    "Timor-Leste": "https://flagcdn.com/tl.svg",
    "Egypt": "https://flagcdn.com/eg.svg",
    "Serbia": "https://flagcdn.com/rs.svg",
    "Mauritius": "https://flagcdn.com/mu.svg",
    "Macau": "https://flagcdn.com/mo.svg",
    "French Polynesia": "https://flagcdn.com/pf.svg",
    "Maldives": "https://flagcdn.com/mv.svg",
    "Indonesia": "https://flagcdn.com/id.svg",
    "DR Congo": "https://flagcdn.com/cd.svg",
    "Estonia": "https://flagcdn.com/ee.svg",
    "Vietnam": "https://flagcdn.com/vn.svg",
    "Italy": "https://flagcdn.com/it.svg",
    "Guinea": "https://flagcdn.com/gn.svg",
    "Chad": "https://flagcdn.com/td.svg",
    "Ecuador": "https://flagcdn.com/ec.svg",
    "Georgia": "https://flagcdn.com/ge.svg",
    "Malawi": "https://flagcdn.com/mw.svg",
    "Iraq": "https://flagcdn.com/iq.svg",
    "Svalbard and Jan Mayen": "https://flagcdn.com/sj.svg",
    "Benin": "https://flagcdn.com/bj.svg",
    "Japan": "https://flagcdn.com/jp.svg",
    "Dominican Republic": "https://flagcdn.com/do.svg",
    "Qatar": "https://flagcdn.com/qa.svg",
    "Gabon": "https://flagcdn.com/ga.svg"
}